import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// #103: capability（src-tauri/capabilities/main.json）の権限不足を静的に検出する。
// ウィンドウモード切替ボタンが、`core:default` に含まれない `set_fullscreen` /
// `set_decorations` の権限が無いために呼び出しを拒否され、何も起きなかった。
// src 内で使う Tauri ウィンドウ API / プラグイン API が、必要な権限をすべて
// main.json で許可されているか（過剰付与の逆＝不足）を突き合わせる。
// 識別子は tauri 2.x の permissions/window/autogenerated/reference.md で裏取り済み。

const ROOT = resolve(fileURLToPath(import.meta.url), '../../..');
const SRC = join(ROOT, 'src');

const capability = JSON.parse(
  readFileSync(join(ROOT, 'src-tauri/capabilities/main.json'), 'utf8'),
) as { permissions: Array<string | { identifier: string }> };
const granted = new Set(
  capability.permissions.map((p) => (typeof p === 'string' ? p : p.identifier)),
);

// 'default' は `core:default` に含まれるため追加不要（読み取り系・イベント購読）。
// それ以外は main.json に明示が必要な権限識別子。
const WINDOW_METHOD_PERMISSIONS: Record<string, string> = {
  // core:default（core:window:default / core:event:default）に含まれる
  isFullscreen: 'default',
  isMaximized: 'default',
  isMinimized: 'default',
  isDecorated: 'default',
  isVisible: 'default',
  innerSize: 'default',
  outerSize: 'default',
  innerPosition: 'default',
  outerPosition: 'default',
  scaleFactor: 'default',
  title: 'default',
  onResized: 'default',
  onMoved: 'default',
  onCloseRequested: 'default',
  listen: 'default',
  // core:default に含まれない（明示が必要）
  setFullscreen: 'core:window:allow-set-fullscreen',
  setDecorations: 'core:window:allow-set-decorations',
  setTitle: 'core:window:allow-set-title',
  setSize: 'core:window:allow-set-size',
  setPosition: 'core:window:allow-set-position',
  setMinSize: 'core:window:allow-set-min-size',
  setMaxSize: 'core:window:allow-set-max-size',
  setResizable: 'core:window:allow-set-resizable',
  setAlwaysOnTop: 'core:window:allow-set-always-on-top',
  setFocus: 'core:window:allow-set-focus',
  setCursorVisible: 'core:window:allow-set-cursor-visible',
  setCursorGrab: 'core:window:allow-set-cursor-grab',
  setIgnoreCursorEvents: 'core:window:allow-set-ignore-cursor-events',
  maximize: 'core:window:allow-maximize',
  unmaximize: 'core:window:allow-unmaximize',
  toggleMaximize: 'core:window:allow-toggle-maximize',
  minimize: 'core:window:allow-minimize',
  unminimize: 'core:window:allow-unminimize',
  hide: 'core:window:allow-hide',
  show: 'core:window:allow-show',
  center: 'core:window:allow-center',
  close: 'core:window:allow-close',
  destroy: 'core:window:allow-destroy',
  startDragging: 'core:window:allow-start-dragging',
};

// プラグイン（JS 側 import）→ 必要な権限（部分一致は不可。許可リストに無い import は失敗）
const PLUGIN_IMPORT_PERMISSIONS: Record<string, string> = {
  '@tauri-apps/plugin-opener': 'opener:allow-open-url',
  '@tauri-apps/plugin-process': 'process:allow-exit',
};

function listSourceFiles(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...listSourceFiles(full));
    else if (/\.(ts|tsx)$/.test(name) && !/\.(test|spec)\.(ts|tsx)$/.test(name)) out.push(full);
  }
  return out;
}

const sources = listSourceFiles(SRC)
  .filter((f) => !f.includes(`${join('src', 'test')}`))
  .map((file) => ({ file, text: readFileSync(file, 'utf8') }));

/** `@tauri-apps/api/window` を import するファイルで呼ばれるウィンドウメソッド名。 */
function usedWindowMethods(): Array<{ file: string; method: string }> {
  const used: Array<{ file: string; method: string }> = [];
  for (const { file, text } of sources) {
    if (!text.includes('@tauri-apps/api/window')) continue;
    // `win.xxx(` と `getCurrentWindow().xxx(`（改行を挟むチェーンを含む）
    const re = /(?:\bwin|\bgetCurrentWindow\(\))\s*\.\s*(\w+)\s*\(/g;
    for (const m of text.matchAll(re)) used.push({ file, method: m[1] });
  }
  return used;
}

describe('capability と src の Tauri API 呼び出しの整合 (#103)', () => {
  it('detects at least the window methods the app is known to call (scanner sanity)', () => {
    const methods = new Set(usedWindowMethods().map((u) => u.method));
    expect(methods.has('setFullscreen')).toBe(true);
    expect(methods.has('setDecorations')).toBe(true);
  });

  it('every window method called in src is known to the permission table', () => {
    const unknown = usedWindowMethods().filter((u) => !(u.method in WINDOW_METHOD_PERMISSIONS));
    expect(unknown).toEqual([]);
  });

  it('every window method called in src has its permission granted in main.json', () => {
    const missing = usedWindowMethods()
      .map((u) => ({ ...u, permission: WINDOW_METHOD_PERMISSIONS[u.method] }))
      .filter((u) => u.permission && u.permission !== 'default' && !granted.has(u.permission))
      .map((u) => `${u.method} -> ${u.permission}`);
    expect([...new Set(missing)]).toEqual([]);
  });

  it('every @tauri-apps/plugin-* import has its permission granted (and is known)', () => {
    const problems: string[] = [];
    for (const { text } of sources) {
      for (const m of text.matchAll(/from\s+'(@tauri-apps\/plugin-[\w-]+)'/g)) {
        const permission = PLUGIN_IMPORT_PERMISSIONS[m[1]];
        if (!permission) problems.push(`${m[1]}: not in permission table`);
        else if (!granted.has(permission)) problems.push(`${m[1]} -> ${permission}`);
      }
    }
    expect([...new Set(problems)]).toEqual([]);
  });

  it('does not grant window permissions that the app does not use (least privilege)', () => {
    const neededByTable = new Set(
      usedWindowMethods().map((u) => WINDOW_METHOD_PERMISSIONS[u.method]),
    );
    const extra = [...granted].filter((p) => p.startsWith('core:window:') && !neededByTable.has(p));
    expect(extra).toEqual([]);
  });
});
