import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// #103: capability（src-tauri/capabilities/main.json）の権限不足を静的に検出する。
// ウィンドウモード切替ボタンが、`core:default` に含まれない `set_fullscreen` /
// `set_decorations` の権限が無いために呼び出しを拒否され、何も起きなかった。
// src 内で使う Tauri ウィンドウ API / プラグイン API が、必要な権限をすべて
// main.json で許可されているか（過剰付与の逆＝不足）を突き合わせる。
// 識別子は tauri 2.x の permissions/window/autogenerated/reference.md で裏取り済み。

const ROOT = resolve(fileURLToPath(import.meta.url), '../../..');
const SRC = join(ROOT, 'src');

const capability = JSON.parse(
  readFileSync(join(ROOT, 'src-tauri/capabilities/main.json'), 'utf8'),
) as { permissions: Array<string | { identifier: string }> };
const granted = new Set(
  capability.permissions.map((p) => (typeof p === 'string' ? p : p.identifier)),
);

// 'default' は `core:default` に含まれるため追加不要（読み取り系・イベント購読）。
// それ以外は main.json に明示が必要な権限識別子。
const WINDOW_METHOD_PERMISSIONS: Record<string, string> = {
  // core:default（core:window:default / core:event:default）に含まれる
  isFullscreen: 'default',
  isMaximized: 'default',
  isMinimized: 'default',
  isDecorated: 'default',
  isVisible: 'default',
  innerSize: 'default',
  outerSize: 'default',
  innerPosition: 'default',
  outerPosition: 'default',
  scaleFactor: 'default',
  title: 'default',
  onResized: 'default',
  onMoved: 'default',
  onCloseRequested: 'default',
  listen: 'default',
  // core:default に含まれない（明示が必要）
  setFullscreen: 'core:window:allow-set-fullscreen',
  setDecorations: 'core:window:allow-set-decorations',
  setTitle: 'core:window:allow-set-title',
  setSize: 'core:window:allow-set-size',
  setPosition: 'core:window:allow-set-position',
  setMinSize: 'core:window:allow-set-min-size',
  setMaxSize: 'core:window:allow-set-max-size',
  setResizable: 'core:window:allow-set-resizable',
  setAlwaysOnTop: 'core:window:allow-set-always-on-top',
  setFocus: 'core:window:allow-set-focus',
  setCursorVisible: 'core:window:allow-set-cursor-visible',
  setCursorGrab: 'core:window:allow-set-cursor-grab',
  setIgnoreCursorEvents: 'core:window:allow-set-ignore-cursor-events',
  maximize: 'core:window:allow-maximize',
  unmaximize: 'core:window:allow-unmaximize',
  toggleMaximize: 'core:window:allow-toggle-maximize',
  minimize: 'core:window:allow-minimize',
  unminimize: 'core:window:allow-unminimize',
  hide: 'core:window:allow-hide',
  show: 'core:window:allow-show',
  center: 'core:window:allow-center',
  close: 'core:window:allow-close',
  destroy: 'core:window:allow-destroy',
  startDragging: 'core:window:allow-start-dragging',
};

// プラグイン（JS 側 import）→ 必要な権限（部分一致は不可。許可リストに無い import は失敗）
const PLUGIN_IMPORT_PERMISSIONS: Record<string, string> = {
  '@tauri-apps/plugin-opener': 'opener:allow-open-url',
  '@tauri-apps/plugin-process': 'process:allow-exit',
};

function listSourceFiles(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...listSourceFiles(full));
    else if (/\.(ts|tsx)$/.test(name) && !/\.(test|spec)\.(ts|tsx)$/.test(name)) out.push(full);
  }
  return out;
}

const sources = listSourceFiles(SRC)
  .filter((f) => !f.includes(`${join('src', 'test')}`))
  .map((file) => ({ file, text: readFileSync(file, 'utf8') }));

const WINDOW_MODULES = ['@tauri-apps/api/window', '@tauri-apps/api/webviewWindow'];

/**
 * ウィンドウ API を import するファイルのソースから、呼ばれているウィンドウメソッド名を返す。
 * 取りこぼしを避けるため、次をすべて拾う。
 * - `getCurrentWindow()` / `getCurrentWebviewWindow()` / `Window.getCurrent()` の直呼びと、
 *   `import { getCurrentWindow as gw }` の別名呼び出しに続くチェーン
 * - それらの戻り値（`new Window(...)` 含む）を代入した変数（`const w = ...`）への呼び出し
 * - 変数名に依らず、対応表にある（=明示権限が要る）メソッド名の `.xxx(` 呼び出し
 */
export function scanWindowMethods(text: string): string[] {
  const factories = ['getCurrentWindow', 'getCurrentWebviewWindow'];
  for (const m of text.matchAll(/\b(getCurrentWindow|getCurrentWebviewWindow)\s+as\s+(\w+)/g)) {
    factories.push(m[2]);
  }
  const factoryAlt = factories.join('|');
  const call = `(?:(?:${factoryAlt})\\s*\\(\\s*\\)|(?:Window|WebviewWindow)\\s*\\.\\s*getCurrent\\s*\\(\\s*\\))`;
  const vars = new Set<string>(['win']);
  const assign = new RegExp(
    `(?:\\b(?:const|let|var)\\s+(\\w+)|\\b(\\w+))\\s*=\\s*(?:await\\s+)?(?:${call}|new\\s+(?:Window|WebviewWindow)\\s*\\()`,
    'g',
  );
  for (const m of text.matchAll(assign)) vars.add(m[1] ?? m[2]);

  const found: string[] = [];
  const chained = new RegExp(
    `(?:\\b(?:${[...vars].join('|')})\\b|${call})\\s*\\.\\s*(\\w+)\\s*\\(`,
    'g',
  );
  for (const m of text.matchAll(chained)) found.push(m[1]);
  const known = Object.keys(WINDOW_METHOD_PERMISSIONS).filter(
    (k) => WINDOW_METHOD_PERMISSIONS[k] !== 'default',
  );
  const anyVar = new RegExp(`\\.\\s*(${known.join('|')})\\s*\\(`, 'g');
  for (const m of text.matchAll(anyVar)) found.push(m[1]);
  return [...new Set(found)];
}

function usedWindowMethods(): Array<{ file: string; method: string }> {
  const used: Array<{ file: string; method: string }> = [];
  for (const { file, text } of sources) {
    if (!WINDOW_MODULES.some((m) => text.includes(m))) continue;
    for (const method of scanWindowMethods(text)) used.push({ file, method });
  }
  return used;
}

describe('scanWindowMethods (#103 スキャナ自体の検証)', () => {
  it('detects direct getCurrentWindow().x() chains, including across newlines', () => {
    expect(scanWindowMethods('getCurrentWindow()\n  .setTitle("a")')).toEqual(['setTitle']);
  });

  it('detects calls through an aliased variable', () => {
    const src = 'const w = getCurrentWindow();\nawait w.setFullscreen(true);';
    expect(scanWindowMethods(src)).toContain('setFullscreen');
  });

  it('detects calls on an unknown-to-table method through an aliased variable', () => {
    const src = 'const w = getCurrentWindow();\nw.setBadgeCount(1);';
    expect(scanWindowMethods(src)).toContain('setBadgeCount');
  });

  it('detects getCurrentWebviewWindow and Window.getCurrent()', () => {
    expect(scanWindowMethods('getCurrentWebviewWindow().hide()')).toEqual(['hide']);
    expect(scanWindowMethods('Window.getCurrent().minimize()')).toEqual(['minimize']);
    expect(scanWindowMethods('const x = Window.getCurrent(); x.close();')).toContain('close');
  });

  it('detects import-aliased factory calls', () => {
    const src =
      "import { getCurrentWindow as gw } from '@tauri-apps/api/window';\ngw().setDecorations(false);";
    expect(scanWindowMethods(src)).toContain('setDecorations');
  });

  it('detects new Window(...) instances and reassigned variables', () => {
    expect(scanWindowMethods("const z = new Window('x'); z.center();")).toContain('center');
    expect(scanWindowMethods('let q; q = getCurrentWindow(); q.maximize();')).toContain('maximize');
  });
});

describe('capability と src の Tauri API 呼び出しの整合 (#103)', () => {
  it('detects at least the window methods the app is known to call (scanner sanity)', () => {
    const methods = new Set(usedWindowMethods().map((u) => u.method));
    expect(methods.has('setFullscreen')).toBe(true);
    expect(methods.has('setDecorations')).toBe(true);
  });

  it('every window method called in src is known to the permission table', () => {
    const unknown = usedWindowMethods().filter((u) => !(u.method in WINDOW_METHOD_PERMISSIONS));
    expect(unknown).toEqual([]);
  });

  it('every window method called in src has its permission granted in main.json', () => {
    const missing = usedWindowMethods()
      .map((u) => ({ ...u, permission: WINDOW_METHOD_PERMISSIONS[u.method] }))
      .filter((u) => u.permission && u.permission !== 'default' && !granted.has(u.permission))
      .map((u) => `${u.method} -> ${u.permission}`);
    expect([...new Set(missing)]).toEqual([]);
  });

  it('every @tauri-apps/plugin-* import has its permission granted (and is known)', () => {
    const problems: string[] = [];
    for (const { text } of sources) {
      for (const m of text.matchAll(/from\s+'(@tauri-apps\/plugin-[\w-]+)'/g)) {
        const permission = PLUGIN_IMPORT_PERMISSIONS[m[1]];
        if (!permission) problems.push(`${m[1]}: not in permission table`);
        else if (!granted.has(permission)) problems.push(`${m[1]} -> ${permission}`);
      }
    }
    expect([...new Set(problems)]).toEqual([]);
  });

  it('does not grant window permissions that the app does not use (least privilege)', () => {
    const neededByTable = new Set(
      usedWindowMethods().map((u) => WINDOW_METHOD_PERMISSIONS[u.method]),
    );
    const extra = [...granted].filter((p) => p.startsWith('core:window:') && !neededByTable.has(p));
    expect(extra).toEqual([]);
  });
});
